DATA_DIR = "data"
STAGING_DIR = "temp/staging"
OUTPUT_DIR = "temp/output"
INPUT_DIR = "temp/input"
MODELS_DIR = "temp/models"
PREVIEW_DIR = "temp/preview"
AMPLITUDE_THRESHOLD = 0
INPUTS = 10
OUTPUTS = 68 * 2
EPOCHS = 20
BATCH_SIZE = 32
TRAIN_VALIDATE_RATIO = 0.2
DATETIME_FORMAT = "%m-%d-%Y-%H:%M:%S"
